// i18n da INTERFACE (dashboard + popup) — pt/en/es. Escolha salva em cfg.ui.idioma
// ("" = auto pelo idioma do navegador). NÃO traduz os status vindos dos content
// scripts (progresso da automação) nem os VALORES de config: "remoto, híbrido,
// presencial" são vocabulário do filtro (localizacao.js casa tokens em pt) e o
// Diagnóstico fica em pt (é lido pelo desenvolvedor).

export const IDIOMAS_UI = { pt: "Português", en: "English", es: "Español" };

const T = {
  // ── Dashboard (options) ─────────────────────────────────────────────────────
  sub: {
    pt: "Tudo que estava no .env se configura aqui. Sem senhas das plataformas: você já está logado no seu navegador.",
    en: "Everything that used to live in .env is configured here. No platform passwords: you're already logged in on your browser.",
    es: "Todo lo que estaba en .env se configura aquí. Sin contraseñas de las plataformas: ya has iniciado sesión en tu navegador.",
  },
  sec_idioma: { pt: "🌐 Idioma da interface", en: "🌐 Interface language", es: "🌐 Idioma de la interfaz" },
  sec_or: { pt: "OpenRouter (IA)", en: "OpenRouter (AI)", es: "OpenRouter (IA)" },
  api_key: { pt: "API Key", en: "API Key", es: "API Key" },
  or_model: { pt: "Modelo (match + respostas)", en: "Model (match + answers)", es: "Modelo (match + respuestas)" },
  or_model_match: { pt: "Modelo p/ match (opcional)", en: "Match model (optional)", es: "Modelo p/ match (opcional)" },
  or_model_match_ph: { pt: "vazio = usa o de cima", en: "empty = uses the one above", es: "vacío = usa el de arriba" },
  testar: { pt: "Testar chave", en: "Test key", es: "Probar clave" },
  sec_ai: { pt: "AssemblyAI (IA)", en: "AssemblyAI (AI)", es: "AssemblyAI (IA)" },
  sec_perfil: {
    pt: "Seu perfil (preenche formulários + gera respostas)",
    en: "Your profile (fills forms + generates answers)",
    es: "Tu perfil (rellena formularios + genera respuestas)",
  },
  p_nome: { pt: "Nome completo", en: "Full name", es: "Nombre completo" },
  p_email: { pt: "E-mail", en: "E-mail", es: "E-mail" },
  p_telefone: { pt: "Telefone / Celular (com DDD)", en: "Phone / Mobile (with area code)", es: "Teléfono / Móvil (con código de área)" },
  p_linkedin: { pt: "LinkedIn (URL)", en: "LinkedIn (URL)", es: "LinkedIn (URL)" },
  p_localizacao: { pt: "Localização", en: "Location", es: "Ubicación" },
  p_cargo: { pt: "Cargo atual", en: "Current role", es: "Cargo actual" },
  p_senioridade: { pt: "Senioridade", en: "Seniority", es: "Senioridad" },
  p_senioridade_ph: { pt: "júnior/pleno/sênior", en: "junior/mid/senior", es: "júnior/semisénior/sénior" },
  p_cv_label: {
    pt: "Resumo do currículo (base das respostas e do match)",
    en: "Resume summary (basis for answers and match)",
    es: "Resumen del currículum (base de las respuestas y del match)",
  },
  p_cv_ph: { pt: "Cole aqui um resumo do seu currículo…", en: "Paste a summary of your resume here…", es: "Pega aquí un resumen de tu currículum…" },
  sec_cv: { pt: "Currículo (arquivo)", en: "Resume (file)", es: "Currículum (archivo)" },
  sec_cv_mut: { pt: "— para upload automático (ex.: GeekHunter)", en: "— for automatic upload (e.g. GeekHunter)", es: "— para subida automática (ej.: GeekHunter)" },
  cv_none: { pt: "nenhum currículo salvo", en: "no resume saved", es: "ningún currículum guardado" },
  cv_salvo: { pt: "✅ salvo:", en: "✅ saved:", es: "✅ guardado:" },
  cv_grande: { pt: "❌ arquivo muito grande (máx 8 MB)", en: "❌ file too large (max 8 MB)", es: "❌ archivo demasiado grande (máx. 8 MB)" },
  cv_nota: {
    pt: "Guardado só no seu navegador. Injetado no campo de upload quando a vaga pedir arquivo. Se o site usar um seletor de arquivo próprio (não um input padrão), pode não funcionar — aí a extensão pausa e você anexa.",
    en: "Stored only in your browser. Injected into the upload field when the job asks for a file. If the site uses a custom file picker (not a standard input) it may not work — the extension pauses and you attach it.",
    es: "Guardado solo en tu navegador. Se inyecta en el campo de subida cuando la vacante pide un archivo. Si el sitio usa un selector de archivos propio (no un input estándar) puede no funcionar — la extensión pausa y tú lo adjuntas.",
  },
  sec_rem: { pt: "Remuneração", en: "Compensation", es: "Remuneración" },
  sec_rem_mut: { pt: "— nunca gerada por IA", en: "— never generated by AI", es: "— nunca generada por IA" },
  p_clt: { pt: "CLT (R$)", en: "CLT (R$)", es: "CLT (R$)" },
  p_pj: { pt: "PJ (R$)", en: "Contractor/PJ (R$)", es: "PJ (R$)" },
  p_usd: { pt: "Dólar (USD)", en: "USD", es: "Dólar (USD)" },
  p_pretensao: { pt: "Pretensão (fallback)", en: "Expected salary (fallback)", es: "Pretensión (fallback)" },
  sec_filtros: { pt: "Filtros", en: "Filters", es: "Filtros" },
  p_modalidades: { pt: "Modalidades aceitas (vírgula)", en: "Accepted work modes (comma)", es: "Modalidades aceptadas (coma)" },
  // os VALORES são vocabulário do filtro — iguais em todo idioma
  p_modalidades_ph: { pt: "remoto, híbrido, presencial", en: "remoto, híbrido, presencial", es: "remoto, híbrido, presencial" },
  p_regioes: { pt: "Regiões p/ presencial/híbrido (vírgula)", en: "Regions for on-site/hybrid (comma)", es: "Regiones p/ presencial/híbrido (coma)" },
  p_regioes_ph: { pt: "SP, RJ", en: "SP, RJ", es: "SP, RJ" },
  pausar_html: {
    pt: "Pausar no envio do <b>Indeed</b> (reCAPTCHA — você confirma). LinkedIn/Gupy/GeekHunter/Senior enviam sozinhos.",
    en: "Pause before submitting on <b>Indeed</b> (reCAPTCHA — you confirm). LinkedIn/Gupy/GeekHunter/Senior submit on their own.",
    es: "Pausar en el envío de <b>Indeed</b> (reCAPTCHA — tú confirmas). LinkedIn/Gupy/GeekHunter/Senior envían solos.",
  },
  sec_plats: { pt: "Plataformas", en: "Platforms", es: "Plataformas" },
  th_ativa: { pt: "Ativa", en: "On", es: "Activa" },
  th_plat: { pt: "Plataforma", en: "Platform", es: "Plataforma" },
  th_query: { pt: "Palavra-chave", en: "Keyword", es: "Palabra clave" },
  th_nota: { pt: "Nota mín. (0-100)", en: "Min. score (0-100)", es: "Nota mín. (0-100)" },
  th_teto: { pt: "Teto/dia", en: "Daily cap", es: "Tope/día" },
  plats_nota: {
    pt: "Todas as plataformas têm content script. LinkedIn é o mais maduro; Indeed/Gupy/GeekHunter/Senior são 1ª versão e os seletores podem precisar de ajuste no 1º run real.",
    en: "All platforms have a content script. LinkedIn is the most mature; Indeed/Gupy/GeekHunter/Senior are first versions and selectors may need tuning on the first real run.",
    es: "Todas las plataformas tienen content script. LinkedIn es la más madura; Indeed/Gupy/GeekHunter/Senior son primeras versiones y los selectores pueden necesitar ajustes en el primer run real.",
  },
  sec_diag: { pt: "Diagnóstico", en: "Diagnostics", es: "Diagnóstico" },
  diag_nota_html: {
    pt: "Quando a automação trava num formulário, ela grava aqui o passo + os campos (nome, tipo, rótulo, obrigatório, valor) e os botões. <b>Baixe o .txt e me mande</b> — é assim que eu vejo o que travou (a extensão não tem console p/ você copiar).",
    en: "When the automation gets stuck on a form, it records here the step + fields (name, type, label, required, value) and buttons. <b>Download the .txt and send it to me</b> — that's how I see what got stuck (the extension has no console for you to copy).",
    es: "Cuando la automatización se atasca en un formulario, graba aquí el paso + los campos (nombre, tipo, etiqueta, obligatorio, valor) y los botones. <b>Descarga el .txt y envíamelo</b> — así veo qué se atascó (la extensión no tiene consola para copiar).",
  },
  diag_atualizar: { pt: "Atualizar", en: "Refresh", es: "Actualizar" },
  diag_copiar: { pt: "Copiar", en: "Copy", es: "Copiar" },
  diag_baixar: { pt: "Baixar .txt", en: "Download .txt", es: "Descargar .txt" },
  diag_limpar: { pt: "Limpar", en: "Clear", es: "Limpiar" },
  diag_vazio: {
    pt: "(sem diagnóstico ainda — rode a automação até travar num formulário)",
    en: "(no diagnostics yet — run the automation until it gets stuck on a form)",
    es: "(sin diagnóstico aún — ejecuta la automatización hasta que se atasque en un formulario)",
  },
  salvar: { pt: "Salvar", en: "Save", es: "Guardar" },
  salvo_ok: { pt: "✅ salvo", en: "✅ saved", es: "✅ guardado" },
  testando: { pt: "testando…", en: "testing…", es: "probando…" },
  informe_chave: { pt: "informe a chave", en: "enter the key", es: "ingresa la clave" },
  chave_ok: { pt: "✅ chave/modelo OK", en: "✅ key/model OK", es: "✅ clave/modelo OK" },

  // ── Popup ───────────────────────────────────────────────────────────────────
  pop_dash: { pt: "⚙️ Dashboard", en: "⚙️ Dashboard", es: "⚙️ Dashboard" },
  pop_dash_title: { pt: "Configurações", en: "Settings", es: "Configuración" },
  pop_warn_html: {
    pt: "⚠️ Configure a <b>OpenRouter API key</b> na dashboard.",
    en: "⚠️ Set your <b>OpenRouter API key</b> in the dashboard.",
    es: "⚠️ Configura la <b>OpenRouter API key</b> en el dashboard.",
  },
  pop_plataforma: { pt: "Plataforma", en: "Platform", es: "Plataforma" },
  pop_start: { pt: "▶️ Iniciar", en: "▶️ Start", es: "▶️ Iniciar" },
  pop_stop: { pt: "⏹️ Parar", en: "⏹️ Stop", es: "⏹️ Detener" },
  pop_startall: { pt: "🚀 Iniciar tudo (todas as plataformas)", en: "🚀 Start all (all platforms)", es: "🚀 Iniciar todo (todas las plataformas)" },
  pop_startall_title: {
    pt: "Abre e roda TODAS as plataformas ao mesmo tempo",
    en: "Opens and runs ALL platforms at the same time",
    es: "Abre y ejecuta TODAS las plataformas al mismo tiempo",
  },
  pop_parado: { pt: "parado", en: "stopped", es: "detenido" },
  pop_rodando: { pt: "rodando", en: "running", es: "en ejecución" },
  pop_iniciando: { pt: "iniciando…", en: "starting…", es: "iniciando…" },
  pop_abrindo: { pt: "abrindo TODAS as plataformas…", en: "opening ALL platforms…", es: "abriendo TODAS las plataformas…" },
  pop_rodando_pfx: { pt: "rodando:", en: "running:", es: "en ejecución:" },
  pop_hoje: { pt: "Hoje", en: "Today", es: "Hoy" },
  pop_erro_start: { pt: "erro ao iniciar", en: "failed to start", es: "error al iniciar" },
  pop_erro_startall: { pt: "erro ao iniciar tudo", en: "failed to start all", es: "error al iniciar todo" },
  pop_footer: {
    pt: "Roda no seu navegador logado. Nada de senha aqui.",
    en: "Runs in your logged-in browser. No passwords here.",
    es: "Se ejecuta en tu navegador con sesión iniciada. Sin contraseñas aquí.",
  },
};

// Idioma efetivo: cfg.ui.idioma salvo, senão o do navegador (pt/en/es), senão en.
export function idiomaUi(cfg) {
  const salvo = cfg?.ui?.idioma;
  if (salvo && IDIOMAS_UI[salvo]) return salvo;
  const nav = (navigator.language || "en").slice(0, 2).toLowerCase();
  return IDIOMAS_UI[nav] ? nav : "en";
}

export function t(lang, key) {
  const e = T[key];
  return (e && (e[lang] || e.pt)) || key;
}

// Aplica nos elementos marcados: data-i18n (textContent), data-i18n-html (innerHTML —
// só strings NOSSAS do dicionário), data-i18n-ph (placeholder), data-i18n-title (title).
export function aplicarI18n(lang, root = document) {
  for (const el of root.querySelectorAll("[data-i18n]")) el.textContent = t(lang, el.dataset.i18n);
  for (const el of root.querySelectorAll("[data-i18n-html]")) el.innerHTML = t(lang, el.dataset.i18nHtml);
  for (const el of root.querySelectorAll("[data-i18n-ph]")) el.placeholder = t(lang, el.dataset.i18nPh);
  for (const el of root.querySelectorAll("[data-i18n-title]")) el.title = t(lang, el.dataset.i18nTitle);
  document.documentElement.lang = { pt: "pt-BR", en: "en", es: "es" }[lang] || lang;
}
